
project_id = "xqghledkjaojfpijpjhn"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "You have been invited"
content_path = ""

[auth.sms]
enable_signup = true
template = "Your code is {{ .Code }} ."

[functions]
[functions.send-contact-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false
