
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqghledkjaojfpijpjhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZ2hsZWRramFvamZwaWpwamhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDk3MzcsImV4cCI6MjA1MzIyNTczN30.YlKPZj96D3JMpw3Oyqt29vw83LxqMMubRoa1WbI4bxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
